WITH report_rows AS (
    SELECT 'baseline_counts' AS check_group, 'mes.work_orders count' AS check_name, 'INFO' AS severity, count(*)::bigint AS finding_count, null::text AS sample_value, 'Baseline row count for comparison.' AS recommendation FROM mes.work_orders
    UNION ALL SELECT 'baseline_counts', 'mes.work_order_events count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.work_order_events
    UNION ALL SELECT 'baseline_counts', 'mes.production_completions count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.production_completions
    UNION ALL SELECT 'baseline_counts', 'mes.vision_events count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.vision_events
    UNION ALL SELECT 'baseline_counts', 'mes.item_station_events count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.item_station_events
    UNION ALL SELECT 'baseline_counts', 'mes.station_queue count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.station_queue
    UNION ALL SELECT 'baseline_counts', 'mes.package_bom_lines count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.package_bom_lines
    UNION ALL SELECT 'baseline_counts', 'mes.package_component_wip count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.package_component_wip
    UNION ALL SELECT 'baseline_counts', 'mes.package_traceability count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.package_traceability
    UNION ALL SELECT 'baseline_counts', 'mes.package_sessions count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.package_sessions
    UNION ALL SELECT 'baseline_counts', 'mes.quality_overrides count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.quality_overrides
    UNION ALL SELECT 'baseline_counts', 'mes.ferp_import_batches count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.ferp_import_batches
    UNION ALL SELECT 'baseline_counts', 'mes.ferp_export_outbox count', 'INFO', count(*)::bigint, null::text, 'Baseline row count for comparison.' FROM mes.ferp_export_outbox
    UNION ALL SELECT 'null_blank_keys', 'mes.work_orders.order_id null or blank', 'FAIL', count(*)::bigint, min(work_order_pk::text), 'Every work order must have order_id.' FROM mes.work_orders WHERE order_id IS NULL OR btrim(order_id) = ''
    UNION ALL SELECT 'null_blank_keys', 'mes.production_completions.external_ref null or blank', 'FAIL', count(*)::bigint, min(completion_pk::text), 'Every production completion needs external_ref.' FROM mes.production_completions WHERE external_ref IS NULL OR btrim(external_ref) = ''
    UNION ALL SELECT 'null_blank_keys', 'mes.vision_events.external_ref null or blank', 'FAIL', count(*)::bigint, min(vision_event_pk::text), 'Every vision event needs external_ref.' FROM mes.vision_events WHERE external_ref IS NULL OR btrim(external_ref) = ''
    UNION ALL SELECT 'null_blank_keys', 'mes.work_order_events.external_ref null or blank', 'FAIL', count(*)::bigint, min(event_pk::text), 'Every work order event needs external_ref.' FROM mes.work_order_events WHERE external_ref IS NULL OR btrim(external_ref) = ''
    UNION ALL SELECT 'null_blank_keys', 'mes.item_station_events source external_ref null or blank', 'FAIL', count(*)::bigint, min(item_station_event_pk::text), 'Station events need source and external_ref.' FROM mes.item_station_events WHERE source IS NULL OR btrim(source) = '' OR external_ref IS NULL OR btrim(external_ref) = ''
    UNION ALL SELECT 'null_blank_keys', 'mes.station_queue required key null or blank', 'FAIL', count(*)::bigint, min(station_queue_pk::text), 'Station queue rows need station_code and order_id.' FROM mes.station_queue WHERE station_code IS NULL OR btrim(station_code) = '' OR order_id IS NULL OR btrim(order_id) = ''
    UNION ALL SELECT 'null_blank_keys', 'mes.package_bom_lines required key null or blank', 'FAIL', count(*)::bigint, min(bom_line_id::text), 'Package BOM runtime rows need package and component stock codes.' FROM mes.package_bom_lines WHERE package_stock_code IS NULL OR btrim(package_stock_code) = '' OR component_stock_code IS NULL OR btrim(component_stock_code) = ''
    UNION ALL SELECT 'null_blank_keys', 'mes.package_component_wip component code null or blank', 'FAIL', count(*)::bigint, min(wip_item_pk::text), 'Component WIP rows need component_stock_code.' FROM mes.package_component_wip WHERE component_stock_code IS NULL OR btrim(component_stock_code) = ''
    UNION ALL SELECT 'null_blank_keys', 'mes.package_traceability required key null or blank', 'FAIL', count(*)::bigint, min(package_trace_pk::text), 'Traceability rows need package_order_id and component_stock_code.' FROM mes.package_traceability WHERE package_order_id IS NULL OR btrim(package_order_id) = '' OR component_stock_code IS NULL OR btrim(component_stock_code) = ''
    UNION ALL SELECT 'null_blank_keys', 'mes.package_sessions required key null or blank', 'FAIL', count(*)::bigint, min(package_order_id), 'Package sessions need session_id, package_order_id and station_code.' FROM mes.package_sessions WHERE session_id IS NULL OR btrim(session_id) = '' OR package_order_id IS NULL OR btrim(package_order_id) = '' OR station_code IS NULL OR btrim(station_code) = ''
    UNION ALL SELECT 'duplicate_keys', 'mes.work_orders duplicate order_id', 'FAIL', count(*)::bigint, min(order_id), 'Resolve duplicate order_id.' FROM (SELECT order_id FROM mes.work_orders WHERE order_id IS NOT NULL AND btrim(order_id) <> '' GROUP BY order_id HAVING count(*) > 1) d
    UNION ALL SELECT 'duplicate_keys', 'mes.production_completions duplicate external_ref', 'FAIL', count(*)::bigint, min(external_ref), 'Resolve duplicate production external_ref.' FROM (SELECT external_ref FROM mes.production_completions WHERE external_ref IS NOT NULL AND btrim(external_ref) <> '' GROUP BY external_ref HAVING count(*) > 1) d
    UNION ALL SELECT 'duplicate_keys', 'mes.vision_events duplicate external_ref', 'FAIL', count(*)::bigint, min(external_ref), 'Resolve duplicate vision external_ref.' FROM (SELECT external_ref FROM mes.vision_events WHERE external_ref IS NOT NULL AND btrim(external_ref) <> '' GROUP BY external_ref HAVING count(*) > 1) d
    UNION ALL SELECT 'duplicate_keys', 'mes.work_order_events duplicate external_ref', 'FAIL', count(*)::bigint, min(external_ref), 'Resolve duplicate transition external_ref.' FROM (SELECT external_ref FROM mes.work_order_events WHERE external_ref IS NOT NULL AND btrim(external_ref) <> '' GROUP BY external_ref HAVING count(*) > 1) d
    UNION ALL SELECT 'duplicate_keys', 'mes.item_station_events duplicate source external_ref', 'FAIL', count(*)::bigint, min(source || ':' || external_ref), 'Resolve duplicate station event idempotency key.' FROM (SELECT source, external_ref FROM mes.item_station_events WHERE source IS NOT NULL AND btrim(source) <> '' AND external_ref IS NOT NULL AND btrim(external_ref) <> '' GROUP BY source, external_ref HAVING count(*) > 1) d
    UNION ALL SELECT 'duplicate_keys', 'mes.package_component_wip duplicate source_external_ref', 'FAIL', count(*)::bigint, min(source_external_ref), 'Resolve duplicate component WIP source reference.' FROM (SELECT source_external_ref FROM mes.package_component_wip WHERE source_external_ref IS NOT NULL AND btrim(source_external_ref) <> '' GROUP BY source_external_ref HAVING count(*) > 1) d
    UNION ALL SELECT 'duplicate_keys', 'mes.package_traceability duplicate external_ref', 'FAIL', count(*)::bigint, min(external_ref), 'Resolve duplicate package traceability external_ref.' FROM (SELECT external_ref FROM mes.package_traceability WHERE external_ref IS NOT NULL AND btrim(external_ref) <> '' GROUP BY external_ref HAVING count(*) > 1) d
    UNION ALL SELECT 'orphan_references', 'mes.work_order_events orphan order_id', 'WARN', count(*)::bigint, min(e.order_id), 'Review transition rows that reference no current work order.' FROM mes.work_order_events e LEFT JOIN mes.work_orders w ON w.order_id = e.order_id WHERE e.order_id IS NOT NULL AND btrim(e.order_id) <> '' AND w.order_id IS NULL
    UNION ALL SELECT 'orphan_references', 'mes.production_completions orphan order_id', 'WARN', count(*)::bigint, min(p.order_id), 'Review completions that reference no current work order.' FROM mes.production_completions p LEFT JOIN mes.work_orders w ON w.order_id = p.order_id WHERE p.order_id IS NOT NULL AND btrim(p.order_id) <> '' AND w.order_id IS NULL
    UNION ALL SELECT 'orphan_references', 'mes.station_queue orphan order_id', 'FAIL', count(*)::bigint, min(q.order_id), 'Station queue rows must reference a current work order.' FROM mes.station_queue q LEFT JOIN mes.work_orders w ON w.order_id = q.order_id WHERE w.order_id IS NULL
    UNION ALL SELECT 'orphan_references', 'mes.item_station_events unknown station_code', 'FAIL', count(*)::bigint, min(e.station_code), 'Station events must reference known stations.' FROM mes.item_station_events e LEFT JOIN mes.stations s ON s.station_code = e.station_code WHERE s.station_code IS NULL
    UNION ALL SELECT 'orphan_references', 'mes.package_sessions orphan package_order_id', 'WARN', count(*)::bigint, min(ps.package_order_id), 'Review package sessions with no matching work order.' FROM mes.package_sessions ps LEFT JOIN mes.work_orders w ON w.order_id = ps.package_order_id WHERE w.order_id IS NULL
    UNION ALL SELECT 'orphan_references', 'mes.package_component_wip orphan reserved_by_session_id', 'WARN', count(*)::bigint, min(wip.reserved_by_session_id), 'Review WIP rows reserved by missing package session.' FROM mes.package_component_wip wip LEFT JOIN mes.package_sessions ps ON ps.session_id = wip.reserved_by_session_id WHERE wip.reserved_by_session_id IS NOT NULL AND btrim(wip.reserved_by_session_id) <> '' AND ps.session_id IS NULL
    UNION ALL SELECT 'orphan_references', 'mes.package_traceability orphan package_session_id', 'WARN', count(*)::bigint, min(pt.package_session_id), 'Review package traceability rows with missing package session.' FROM mes.package_traceability pt LEFT JOIN mes.package_sessions ps ON ps.session_id = pt.package_session_id WHERE pt.package_session_id IS NOT NULL AND btrim(pt.package_session_id) <> '' AND ps.session_id IS NULL
    UNION ALL SELECT 'status_distribution', 'mes.work_orders status distribution', 'INFO', count(*)::bigint, coalesce(status, '<null>'), 'Review status values before read transition.' FROM mes.work_orders GROUP BY status
    UNION ALL SELECT 'status_distribution', 'mes.station_queue status distribution', 'INFO', count(*)::bigint, coalesce(status, '<null>'), 'Review queue status values.' FROM mes.station_queue GROUP BY status
    UNION ALL SELECT 'status_distribution', 'mes.package_component_wip status distribution', 'INFO', count(*)::bigint, coalesce(status, '<null>'), 'Review package WIP status values.' FROM mes.package_component_wip GROUP BY status
    UNION ALL SELECT 'status_distribution', 'mes.package_sessions status distribution', 'INFO', count(*)::bigint, coalesce(status, '<null>'), 'Review package session status values.' FROM mes.package_sessions GROUP BY status
    UNION ALL SELECT 'status_distribution', 'mes.quality_overrides classification distribution', 'INFO', count(*)::bigint, coalesce(classification, '<null>'), 'Review quality classification values.' FROM mes.quality_overrides GROUP BY classification
    UNION ALL SELECT 'timestamp_sanity', 'mes.work_orders future started_at', 'WARN', count(*)::bigint, min(work_order_pk::text), 'Review future started_at values.' FROM mes.work_orders WHERE started_at > now() + interval '5 minutes'
    UNION ALL SELECT 'timestamp_sanity', 'mes.work_orders completed before started', 'FAIL', count(*)::bigint, min(work_order_pk::text), 'completed_at must not be before started_at.' FROM mes.work_orders WHERE started_at IS NOT NULL AND completed_at IS NOT NULL AND completed_at < started_at
    UNION ALL SELECT 'timestamp_sanity', 'mes.production_completions future completed_at', 'WARN', count(*)::bigint, min(completion_pk::text), 'Review future completion timestamps.' FROM mes.production_completions WHERE completed_at > now() + interval '5 minutes'
    UNION ALL SELECT 'timestamp_sanity', 'mes.vision_events future detected_at', 'WARN', count(*)::bigint, min(vision_event_pk::text), 'Review future vision timestamps.' FROM mes.vision_events WHERE detected_at > now() + interval '5 minutes'
    UNION ALL SELECT 'timestamp_sanity', 'mes.oee_snapshots future snapshot_at', 'WARN', count(*)::bigint, min(snapshot_pk::text), 'Review future OEE snapshots.' FROM mes.oee_snapshots WHERE snapshot_at > now() + interval '5 minutes'
    UNION ALL SELECT 'timestamp_sanity', 'mes.package_sessions finished before started', 'FAIL', count(*)::bigint, min(session_id), 'finished_at must not be before started_at.' FROM mes.package_sessions WHERE started_at IS NOT NULL AND finished_at IS NOT NULL AND finished_at < started_at
    UNION ALL SELECT 'timestamp_sanity', 'mes.package_bom_lines invalid valid window', 'FAIL', count(*)::bigint, min(bom_line_id::text), 'valid_to must be after valid_from.' FROM mes.package_bom_lines WHERE valid_to IS NOT NULL AND valid_to <= valid_from
    UNION ALL SELECT 'station_queue_consistency', 'mes.station_queue duplicate station order', 'FAIL', count(*)::bigint, min(station_code || ':' || order_id), 'Resolve duplicate station/order queue rows.' FROM (SELECT station_code, order_id FROM mes.station_queue GROUP BY station_code, order_id HAVING count(*) > 1) d
    UNION ALL SELECT 'station_queue_consistency', 'mes.station_queue duplicate active rank', 'FAIL', count(*)::bigint, min(station_code || ':' || queue_rank::text), 'Resolve active queue rank collision.' FROM (SELECT station_code, queue_rank FROM mes.station_queue WHERE status IN ('queued', 'active', 'pending_approval') GROUP BY station_code, queue_rank HAVING count(*) > 1) d
    UNION ALL SELECT 'station_queue_consistency', 'mes.station_queue negative queue_rank', 'FAIL', count(*)::bigint, min(station_queue_pk::text), 'queue_rank must be zero or positive.' FROM mes.station_queue WHERE queue_rank < 0
    UNION ALL SELECT 'package_runtime_consistency', 'mes.package_bom_lines active component duplicate', 'FAIL', count(*)::bigint, min(package_stock_code || ':' || component_stock_code), 'Resolve duplicate active package component rows.' FROM (SELECT package_stock_code, component_stock_code FROM mes.package_bom_lines WHERE active GROUP BY package_stock_code, component_stock_code HAVING count(*) > 1) d
    UNION ALL SELECT 'package_runtime_consistency', 'mes.package_bom_lines required_qty not positive', 'FAIL', count(*)::bigint, min(bom_line_id::text), 'required_qty must be positive.' FROM mes.package_bom_lines WHERE required_qty <= 0
    UNION ALL SELECT 'package_runtime_consistency', 'mes.package_traceability component_qty not positive', 'FAIL', count(*)::bigint, min(package_trace_pk::text), 'component_qty must be positive.' FROM mes.package_traceability WHERE component_qty <= 0
    UNION ALL SELECT 'package_runtime_consistency', 'mes.package_sessions open session duplicate risk', 'WARN', count(*)::bigint, min(package_order_id || ':' || station_code), 'Review multiple unfinished sessions for same package order and station.' FROM (SELECT package_order_id, station_code FROM mes.package_sessions WHERE finished_at IS NULL GROUP BY package_order_id, station_code HAVING count(*) > 1) d
)
SELECT
    check_group,
    check_name,
    severity,
    finding_count,
    sample_value,
    recommendation
FROM report_rows
ORDER BY check_group, check_name, sample_value;
